// TanStack Start route template — copy to src/routes/<slug>.tsx and fill in:
//   * ROUTE_PATH         — e.g. "/about"
//   * PAGE_TITLE / DESC  — unique per route
//   * BODY_HTML          — generated by scripts/extract_body.py
//   * PAGE_CSS           — page-specific CSS files in public/css/
//   * PAGE_SCRIPTS       — page-specific JS files in public/js/
import { createFileRoute } from "@tanstack/react-router";
import { useEffect } from "react";

const BODY_HTML = ""; // replace with extractor output

const PAGE_CSS: string[] = [
  "/css/preload.min.css",
  "/css/icomoon.css",
  "/css/libs.min.css",
  // "/css/<page>.min.css",
];

const PAGE_SCRIPTS: string[] = [
  "/js/common.min.js",
  // "/js/<page>.min.js",
];

export const Route = createFileRoute("/REPLACE_ROUTE_PATH" as never)({
  head: () => ({
    meta: [
      { title: "REPLACE_PAGE_TITLE" },
      { name: "description", content: "REPLACE_PAGE_DESCRIPTION" },
      { property: "og:title", content: "REPLACE_PAGE_TITLE" },
      { property: "og:description", content: "REPLACE_PAGE_DESCRIPTION" },
    ],
    links: PAGE_CSS.map((href) => ({ rel: "stylesheet", href })),
    scripts: PAGE_SCRIPTS.map((src) => ({ src, defer: true })),
  }),
  component: Page,
});

function Page() {
  useEffect(() => {
    // Re-append scripts on SPA nav so vanilla JS (sliders, menus) re-inits.
    const added: HTMLScriptElement[] = [];
    PAGE_SCRIPTS.forEach((src) => {
      const s = document.createElement("script");
      s.src = src;
      s.async = false; // preserve execution order
      document.body.appendChild(s);
      added.push(s);
    });
    return () => {
      added.forEach((s) => s.remove());
    };
  }, []);

  return (
    <div
      style={{ display: "contents" }}
      dangerouslySetInnerHTML={{ __html: BODY_HTML }}
    />
  );
}
